import "@/styles/globals.css";
import NavBar from "@/components/common/nav-bar";
import Footer from "@/components/common/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="flex flex-col min-h-screen">
          <main className="flex-grow my-4 md:mx-12 mx-8">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
